# Generated by Django 2.2.16 on 2022-08-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления'),
        ),
    ]
