# Generated by Django 3.2.16 on 2022-10-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221009_2118'),
        ('recipes', '0010_shoppinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingCart',
        ),
    ]
